from app.schemas.blog import BlogCreate


VERIFIED_VELOPERS_BLOG_PRESETS: list[BlogCreate] = [
    BlogCreate(
        name="우아한 형제들",
        company="우아한형제들",
        description="우아한형제들 기술 블로그",
        rss_url="https://techblog.woowahan.com/feed",
        site_url="https://techblog.woowahan.com/",
    ),
    BlogCreate(
        name="토스",
        company="토스",
        description="토스 기술 블로그",
        rss_url="https://toss.tech/rss.xml",
        site_url="https://toss.tech/",
    ),
    BlogCreate(
        name="가비아",
        company="가비아",
        description="가비아 기술/라이브러리 블로그",
        rss_url="https://library.gabia.com/rss.xml",
        site_url="https://library.gabia.com/",
    ),
    BlogCreate(
        name="네이버 플레이스",
        company="네이버",
        description="네이버 플레이스 개발 블로그",
        rss_url="https://medium.com/naver-place-dev/feed",
        site_url="https://medium.com/naver-place-dev",
    ),
    BlogCreate(
        name="넷마블",
        company="넷마블",
        description="넷마블 엔지니어링 블로그",
        rss_url="https://netmarble.engineering/feed",
        site_url="https://netmarble.engineering/",
    ),
    BlogCreate(
        name="당근마켓",
        company="당근",
        description="당근 기술 블로그",
        rss_url="https://medium.com/daangn/feed",
        site_url="https://medium.com/daangn",
    ),
    BlogCreate(
        name="SSG.COM",
        company="SSG.COM",
        description="SSG.COM 기술 블로그",
        rss_url="https://medium.com/ssgtech/feed",
        site_url="https://medium.com/ssgtech",
    ),
    BlogCreate(
        name="무신사",
        company="무신사",
        description="무신사 기술 블로그",
        rss_url="https://medium.com/musinsa-tech/feed",
        site_url="https://medium.com/musinsa-tech",
    ),
    BlogCreate(
        name="마켓컬리",
        company="컬리",
        description="컬리 기술 블로그",
        rss_url="https://helloworld.kurly.com/rss.xml",
        site_url="https://helloworld.kurly.com",
    ),
    BlogCreate(
        name="카카오엔터프라이즈",
        company="카카오엔터프라이즈",
        description="카카오엔터프라이즈 기술 블로그",
        rss_url="https://tech.kakaoenterprise.com/feed",
        site_url="https://tech.kakaoenterprise.com",
    ),
    BlogCreate(
        name="데브시스터즈",
        company="데브시스터즈",
        description="데브시스터즈 기술 블로그",
        rss_url="https://tech.devsisters.com/rss.xml",
        site_url="https://tech.devsisters.com",
    ),
    BlogCreate(
        name="카카오",
        company="카카오",
        description="카카오 기술 블로그",
        rss_url="https://tech.kakao.com/blog/feed",
        site_url="https://tech.kakao.com/blog",
    ),
    BlogCreate(
        name="뱅크샐러드",
        company="뱅크샐러드",
        description="뱅크샐러드 기술 블로그",
        rss_url="https://blog.banksalad.com/rss.xml",
        site_url="https://blog.banksalad.com",
    ),
    BlogCreate(
        name="쏘카",
        company="쏘카",
        description="쏘카 기술 블로그",
        rss_url="https://tech.socarcorp.kr/feed.xml",
        site_url="https://tech.socarcorp.kr",
    ),
    BlogCreate(
        name="RIDI",
        company="리디",
        description="리디 기술 블로그",
        rss_url="https://ridicorp.com/story-category/tech-blog/feed",
        site_url="https://ridicorp.com/story-category/tech-blog/",
    ),
    BlogCreate(
        name="카카오페이",
        company="카카오페이",
        description="카카오페이 기술 블로그",
        rss_url="https://tech.kakaopay.com/rss.xml",
        site_url="https://tech.kakaopay.com",
    ),
    BlogCreate(
        name="여기어때",
        company="여기어때",
        description="여기어때 기술 블로그",
        rss_url="https://techblog.gccompany.co.kr/feed.xml",
        site_url="https://techblog.gccompany.co.kr/",
    ),
    BlogCreate(
        name="올리브영",
        company="CJ 올리브영",
        description="올리브영 기술 블로그",
        rss_url="https://oliveyoung.tech/blog/rss.xml",
        site_url="https://oliveyoung.tech/blog",
    ),
    BlogCreate(
        name="카카오뱅크",
        company="카카오뱅크",
        description="카카오뱅크 기술 블로그",
        rss_url="https://tech.kakaobank.com/index.xml",
        site_url="https://tech.kakaobank.com",
    ),
    BlogCreate(
        name="인포그랩",
        company="인포그랩",
        description="인포그랩 인사이트 블로그",
        rss_url="https://insight.infograb.net/blog/rss.xml",
        site_url="https://insight.infograb.net/blog",
    ),
    BlogCreate(
        name="요기요",
        company="요기요",
        description="요기요 기술 블로그",
        rss_url="https://techblog.yogiyo.co.kr/feeds/posts/default?alt=rss",
        site_url="https://techblog.yogiyo.co.kr/",
    ),
]
