# Admin Web 모듈 전용 설정
app:
  admin:
    username: admin
    password: admin123

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker

app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}