"""add_post_status_and_processing_fields

Revision ID: d5fca864f1a2
Revises: dce24ac41323
Create Date: 2025-11-24 13:34:15.134147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fca864f1a2'
down_revision: Union[str, Sequence[str], None] = 'dce24ac41323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM type first
    post_status_enum = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='post_status')
    post_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='post_status'), nullable=False, server_default='PENDING', comment='본문 추출 상태'))
    op.add_column('posts', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False, comment='본문 추출 재시도 횟수'))
    op.add_column('posts', sa.Column('error_message', sa.Text(), nullable=True, comment='추출 실패 시 에러 메시지'))
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_column('posts', 'error_message')
    op.drop_column('posts', 'retry_count')
    op.drop_column('posts', 'status')

    # Drop ENUM type
    post_status_enum = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='post_status')
    post_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
