"""Create blogs and posts tables

Revision ID: dce24ac41323
Revises: 
Create Date: 2025-11-22 20:54:43.499376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dce24ac41323'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='블로그 이름'),
    sa.Column('company', sa.String(length=255), nullable=False, comment='회사/개인 이름'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='블로그 설명'),
    sa.Column('rss_url', sa.String(length=500), nullable=False, comment='RSS 피드 URL'),
    sa.Column('site_url', sa.String(length=500), nullable=False, comment='블로그 사이트 URL'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='로고 이미지 URL'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='blog_status'), nullable=False, comment='블로그 상태'),
    sa.Column('blog_type', sa.Enum('COMPANY', 'PERSONAL', name='blog_type'), nullable=True, comment='블로그 타입'),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 크롤링 시각'),
    sa.Column('failure_count', sa.Integer(), nullable=True, comment='크롤링 실패 횟수'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=False)
    op.create_index(op.f('ix_blogs_name'), 'blogs', ['name'], unique=True)
    op.create_index(op.f('ix_blogs_rss_url'), 'blogs', ['rss_url'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='게시글 제목'),
    sa.Column('content', sa.Text(), nullable=True, comment='게시글 본문 (HTML 또는 Markdown)'),
    sa.Column('author', sa.String(length=200), nullable=True, comment='작성자'),
    sa.Column('original_url', sa.String(length=1000), nullable=False, comment='원본 게시글 URL'),
    sa.Column('normalized_url', sa.String(length=1000), nullable=True, comment='정규화된 URL (쿼리 파라미터 제거)'),
    sa.Column('blog_id', sa.Integer(), nullable=False, comment='블로그 ID'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='게시글 발행 시각'),
    sa.Column('keyword_vector', postgresql.TSVECTOR(), nullable=True, comment='키워드 검색을 위한 tsvector'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_blog_published', 'posts', ['blog_id', 'published_at'], unique=False)
    op.create_index('idx_posts_keyword_vector', 'posts', ['keyword_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_posts_blog_id'), 'posts', ['blog_id'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_normalized_url'), 'posts', ['normalized_url'], unique=True)
    op.create_index(op.f('ix_posts_original_url'), 'posts', ['original_url'], unique=True)
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_original_url'), table_name='posts')
    op.drop_index(op.f('ix_posts_normalized_url'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_blog_id'), table_name='posts')
    op.drop_index('idx_posts_keyword_vector', table_name='posts', postgresql_using='gin')
    op.drop_index('idx_posts_blog_published', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_blogs_rss_url'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_name'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
