# Batch 모듈 전용 설정
app:
  # 자동 태깅 설정
  autotag:
    enabled: true
    batch-size: 10
    schedule: "0 0 * * * ?"  # 매시 정각
    
  # RSS 크롤링 설정
  crawler:
    enabled: true
    schedule:
      # 매일 오전 6시에 모든 활성 블로그 크롤링
      all-blogs: "0 0 6 * * ?"
      # 매시 정각에 크롤링이 필요한 블로그들만 크롤링
      needed-blogs: "0 0 * * * ?"
      # 매일 오후 11시에 통계 로깅 (선택적)
      stats: "0 0 23 * * ?"
    stats:
      enabled: false
    http:
      timeout-seconds: 30
      user-agent: "TechBlogHub-Crawler/1.0"
      max-posts-per-feed: 50