# Persistence 모듈 - 환경별 설정은 PersistenceEnvironmentConfig에서 관리
spring:
  datasource:
    url: ${database.url}
    driver-class-name: ${database.driver-class-name}
    username: ${database.username}
    password: ${database.password}
  
  jpa:
    database-platform: ${jpa.database-platform}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: ${jpa.hibernate.ddl-auto}
    show-sql: ${jpa.show-sql}
    properties:
      hibernate:
        format_sql: ${jpa.hibernate.format-sql}
        default_batch_fetch_size: ${jpa.hibernate.default-batch-fetch-size}
        order_inserts: ${jpa.hibernate.order-inserts}
        order_updates: ${jpa.hibernate.order-updates}
        jdbc:
          batch_size: ${jpa.hibernate.jdbc.batch-size}
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: ${sql.init.mode}