# Database Configuration
database:
  host: localhost
  port: 5432
  database: techbloghub
  username: admin
  password: password

# Processing Configuration
processing:
  batch_size: 10
  retry_attempts: 3
  delay_between_requests: 1.0
  content_min_length: 1000
  requests_per_second: 1
  timeout_seconds: 30

# OpenAI Configuration
openai:
  model: gpt-4o-mini
  temperature: 0.1
  max_tokens: 4000

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/content_processor.log
  max_file_size: 10485760 # 10MB
  backup_count: 5

# Content Processing
content:
  chunk_size: 3000
  chunk_overlap: 300
  remove_selectors:
    - header
    - footer
    - nav
    - .ads
    - .advertisement
    - script
    - style
    - .social
    - .share
    - .comments

# Summary Template
summary:
  template: |
    다음의 내용을 한글로 요약해줘:

    {text}

  combine_template: |
    다음 웹 페이지 콘텐츠를 분석하여 핵심 내용을 요약해주세요.
            
    웹 페이지 콘텐츠:
    {text}

    요약 지침:
    1. 주요 내용과 핵심 포인트를 3-5개의 불릿 포인트로 요약
    2. 기술적 내용이 있다면 중요한 기술 스택이나 개념 포함
    3. 실용적이고 유용한 정보 위주로 요약
    4. 200-300자 내외로 간결하게 작성
    5. 한국어로 작성

    요약:
