# Batch 모듈 - 환경별 설정은 BatchEnvironmentConfig에서 관리
app:
  crawler:
    enabled: ${app.crawler.enabled}
    schedule:
      all-blogs: ${app.crawler.schedule.all-blogs}
      needed-blogs: ${app.crawler.schedule.needed-blogs}
      stats: ${app.crawler.schedule.stats}
    stats:
      enabled: ${app.crawler.stats.enabled}
    http:
      timeout-seconds: ${app.crawler.http.timeout-seconds}
      user-agent: ${app.crawler.http.user-agent}
      max-posts-per-feed: ${app.crawler.http.max-posts-per-feed}