version: '3.8'

services:
  content-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: content-processor
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./config/config.docker.yaml:/app/config/config.yaml:ro
    networks:
      - docker_techblog-network
    # Override default command for testing
    command: ["python", "main.py", "--max-batches", "1", "--dry-run"]

networks:
  docker_techblog-network:
    external: true