spring:
  application:
    name: techbloghub-backend
  
  profiles:
    active: local
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  
  security:
    user:
      name: admin
      password: admin123

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

logging:
  level:
    com.techbloghub: DEBUG

# 크롤링 스케줄러 설정
crawler:
  schedule:
    enabled: true
    hourly-cron: "0 0 * * * *"  # 매시간 0분에 실행
    daily-cron: "0 0 6 * * *"   # 매일 오전 6시에 실행

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/techbloghub}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  

---
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  

logging:
  level:
    root: INFO
    com.techbloghub: INFO